name: vscode-insiders-release

on:
  push:
    tags:
      - vscode-v* # automatically create a new insider build with a release
  workflow_dispatch:

jobs:
  release:
    if: (github.ref == 'refs/heads/custom-builds' || github.event_name == 'workflow_dispatch') && github.repository == 'PriNova/cody'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get all tags
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # SECURITY: pin third-party action hashes
        with:
          run_install: true
      - run: pnpm build
      - run: CODY_RELEASE_TYPE=insiders pnpm -C vscode run release:dry-run
      
      # Replace the Create Release step with this
      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
      # Replace the Create Release step with this
      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./vscode/dist/cody-custom.vsix
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
            
            Automated release from tag push
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
